#!/usr/bin/awk -f

BEGIN {
    while ((getline i < "proto.h") > 0) old_protos = old_protos ? old_protos "\n" i : i
    close("proto.h")
    protos = "/* This file is automatically generated with \"make proto\". DO NOT EDIT */\n"
    protos = protos "\n/* OpenCog forward type declarations */\n"
    protos = protos "typedef enum cog_agent_type cog_agent_type;\n"
    protos = protos "typedef enum cog_msg_type cog_msg_type;\n"
    protos = protos "typedef enum atom_type atom_type;\n"
    protos = protos "typedef enum link_type link_type;\n"
    protos = protos "typedef enum swarm_state swarm_state;\n"
    protos = protos "struct cog_agent;\n"
    protos = protos "struct atom_space;\n"
    protos = protos "struct atom;\n"
    protos = protos "struct swarm_formation;\n"
    protos = protos "typedef int (*cog_task_handler)(struct cog_agent *agent, void *task_data);\n"
    protos = protos "\n"
}

inheader {
    protos = protos "\n" ((inheader = /\)[ \t]*$/ ? 0 : 1) ? $0 : $0 ";")
    next
}

/^FN_(LOCAL|GLOBAL)_[^(]+\([^,()]+/ {
    local = /^FN_LOCAL/
    gsub(/^FN_(LOC|GLOB)AL_|,.*$/, "")
    sub(/^BOOL\(/, "BOOL ")
    sub(/^CHAR\(/, "char ")
    sub(/^INTEGER\(/, "int ")
    sub(/^STRING\(/, "char *")
    protos = protos "\n" $0 (local ? "(int module_id);" : "(void);")
    next
}

/^static|^extern|;/||!/^[A-Za-z][A-Za-z0-9_]* / { next }

/\(.*\)[ \t]*$/ {
    protos = protos "\n" $0 ";"
    next
}

/\(/ {
    inheader = 1
    protos = protos "\n" $0
}

END {
    if (old_protos != protos) print protos > "proto.h"
    system("touch proto.h-tstamp")
}
